[versions]
# libraries
junit = "4.13.2"

# plugins
# https://github.com/JetBrains/intellij-platform-gradle-plugin
intelliJPlatform = "2.10.5"
# https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#bundled-stdlib-versions
kotlin = "2.1.20"
# Grammar-Kit Gradle plugin
grammarKit = "2023.3.0.1"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarKit = { id = "org.jetbrains.grammarkit", version.ref = "grammarKit" }
